/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorPreviewRouteImport } from './routes/error-preview'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SheetsIndexRouteImport } from './routes/sheets/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as NpcsIndexRouteImport } from './routes/npcs/index'
import { Route as LoreIndexRouteImport } from './routes/lore/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as SheetsCharacterIdRouteImport } from './routes/sheets/$characterId'

const ErrorPreviewRoute = ErrorPreviewRouteImport.update({
  id: '/error-preview',
  path: '/error-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetsIndexRoute = SheetsIndexRouteImport.update({
  id: '/sheets/',
  path: '/sheets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsIndexRoute = NpcsIndexRouteImport.update({
  id: '/npcs/',
  path: '/npcs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreIndexRoute = LoreIndexRouteImport.update({
  id: '/lore/',
  path: '/lore/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetsCharacterIdRoute = SheetsCharacterIdRouteImport.update({
  id: '/sheets/$characterId',
  path: '/sheets/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/error-preview': typeof ErrorPreviewRoute
  '/sheets/$characterId': typeof SheetsCharacterIdRoute
  '/characters': typeof CharactersIndexRoute
  '/items': typeof ItemsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/lore': typeof LoreIndexRoute
  '/npcs': typeof NpcsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/sheets': typeof SheetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/error-preview': typeof ErrorPreviewRoute
  '/sheets/$characterId': typeof SheetsCharacterIdRoute
  '/characters': typeof CharactersIndexRoute
  '/items': typeof ItemsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/lore': typeof LoreIndexRoute
  '/npcs': typeof NpcsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/sheets': typeof SheetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/error-preview': typeof ErrorPreviewRoute
  '/sheets/$characterId': typeof SheetsCharacterIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/lore/': typeof LoreIndexRoute
  '/npcs/': typeof NpcsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sheets/': typeof SheetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/error-preview'
    | '/sheets/$characterId'
    | '/characters'
    | '/items'
    | '/locations'
    | '/lore'
    | '/npcs'
    | '/sessions'
    | '/sheets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/error-preview'
    | '/sheets/$characterId'
    | '/characters'
    | '/items'
    | '/locations'
    | '/lore'
    | '/npcs'
    | '/sessions'
    | '/sheets'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/error-preview'
    | '/sheets/$characterId'
    | '/characters/'
    | '/items/'
    | '/locations/'
    | '/lore/'
    | '/npcs/'
    | '/sessions/'
    | '/sheets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ErrorPreviewRoute: typeof ErrorPreviewRoute
  SheetsCharacterIdRoute: typeof SheetsCharacterIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  LoreIndexRoute: typeof LoreIndexRoute
  NpcsIndexRoute: typeof NpcsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SheetsIndexRoute: typeof SheetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error-preview': {
      id: '/error-preview'
      path: '/error-preview'
      fullPath: '/error-preview'
      preLoaderRoute: typeof ErrorPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheets/': {
      id: '/sheets/'
      path: '/sheets'
      fullPath: '/sheets'
      preLoaderRoute: typeof SheetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs/': {
      id: '/npcs/'
      path: '/npcs'
      fullPath: '/npcs'
      preLoaderRoute: typeof NpcsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore/': {
      id: '/lore/'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheets/$characterId': {
      id: '/sheets/$characterId'
      path: '/sheets/$characterId'
      fullPath: '/sheets/$characterId'
      preLoaderRoute: typeof SheetsCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ErrorPreviewRoute: ErrorPreviewRoute,
  SheetsCharacterIdRoute: SheetsCharacterIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  LoreIndexRoute: LoreIndexRoute,
  NpcsIndexRoute: NpcsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SheetsIndexRoute: SheetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
